### ISSUE TITLE
Bild zu bereits verfassten Beitrag hinzufügen

### ISSUE THREAD

**Issue by lorenzSt** [sweIhm/sweiproject-tg1b-5#10]
Als ehemaliger Austauschschüler möchte ich ein Bild zu einem meiner alten Beitrage hinzufügen.

Akzeptanzkriterien:

- Email verifizieren
- Beitrag muss erkennen, dass der User den ursprünglichen Post geschrieben hat
- Bild muss hochgeladen werden können
- Bild muss zum Post hinzugefügt werden
- neuer Post muss angezeigt werden

**Comment by hsiehken** [comment]
duplicated issue
