### ISSUE TITLE
Bild hochladen

### ISSUE THREAD

**Issue by lorenzSt** [sweIhm/sweiproject-tg1b-5#11]
Als User möchte ich ein Bild hochladen, um es später zu einem Beitrag hinzuzufügen.

Akzeptanzkriterien:

- Schnittstelle zum hochladen des Files
- Überprüfen des Files, ob die Eigenschaften zulässig sind (Format, Größe)
- Zwischenspeichern bis es vom User verwendet wird

**Comment by hsiehken** [comment]
Fully tested.
