### ISSUE TITLE
Beiträge nach Zeit sortieren

### ISSUE THREAD

**Issue by lorenzSt** [sweIhm/sweiproject-tg1b-5#12]
Als User möchte ich die neuesten Beiträge und Aktivitäten zuerst sehen.

Akzeptanzkriterien:

- Beitrage müssen nach Zeit sortiert werden
- Beiträge müssen in der neuen Reihenfolge angezeigt werden

**Comment by hsiehken** [comment]
Code ferig, braucht noch tests

**Comment by hsiehken** [comment]
Test passed, well done.
