### ISSUE TITLE
Beiträge nach Tags sortieren

### ISSUE THREAD

**Issue by 21Spawn** [sweIhm/sweiproject-tg1b-5#16]
Als User möchte ich die Beiträge nach Tags sortieren.

Akzeptanzkriterien:

-Beitrage müssen nach Tags sortiert werden
-Beiträge müssen in der neuen Reihenfolge angezeigt werden

**Comment by hsiehken** [comment]
Tag class can't be serized by Spring Boot while creating a new activity.

**Comment by hsiehken** [comment]
Fully tested.
