### ISSUE TITLE
Anforderung zum löschen von Beiträgen

### ISSUE THREAD

**Issue by 21Spawn** [sweIhm/sweiproject-tg1b-5#19]
Als User möchte ich eine Anforderung an den Datenbankverwalter senden, um unpassende Beiträge zu löschen.

Akzeptanzkriterien:

- Admin erhält Anfrage mit den gewünschten Beitrag

- Falls der Beitrag unpassend, ist wird er vom datenbankverwalter gelöscht

**Comment by hsiehken** [comment]
duplicated issue
