### ISSUE TITLE
Beitrag verfassen

### ISSUE THREAD

**Issue by lorenzSt** [sweIhm/sweiproject-tg1b-5#2]
Als ehemaliger Austauschschüler will ich einen Bericht posten, um Erfahrungen zu teilen.

Akzeptanzkriterien:

- Post verfassen
- Post posten
- Post wird Lesern angezeigt

**Comment by hsiehken** [comment]
Code ferig, braucht noch tests.

**Comment by hsiehken** [comment]
Test passed, well done.
