### ISSUE TITLE
Beiträge nach Tags sortieren

### ISSUE THREAD

**Issue by lorenzSt** [sweIhm/sweiproject-tg1b-5#21]
Als Austausch-Interessierter sollen mir alle Beiträge mit den Tags #Erfahrungsbericht und #MIT angezeigt werden.

Akzeptanzkriterien:

- Eingabe für Tags nach denen gesucht werden soll
- Beiträge werden sortiert je nachdem wie viele der gesuchten Tags aufgeführt sind
- Beiträge werden nach dieser Reihenfolge angezeigt

**Comment by hsiehken** [comment]
duplicated issue
