### ISSUE TITLE
Tags zu Beitrag hinzufügen

### ISSUE THREAD

**Issue by lorenzSt** [sweIhm/sweiproject-tg1b-5#23]
Als Verfasser eines Posts möchte ich ein Tags zu einem Post hinzufügen.

Akzeptanzkriterien:

- Es muss eine Zeile zum Eintragen der Tags geben
- Wörter in der Zeile müssen als einzelne Tags erkannt werden

**Comment by hsiehken** [comment]
duplicated issue
