### ISSUE TITLE
Email verifizieren

### ISSUE THREAD

**Issue by lorenzSt** [sweIhm/sweiproject-tg1b-5#3]
Als ehemaliger Austauschschüler möchte ich meine Email verifizieren lassen, um einen Beitrag zu schreiben.

Akzeptanzkriterien:
-Email-Adresse eingeben
-Email mit Verifizierungscode senden
-Verifizierungscode eingeben können
-Weiterleitung zum Postformular

**Comment by hsiehken** [comment]
done!
