### ISSUE TITLE
Alten Beitrag ändern

### ISSUE THREAD

**Issue by lorenzSt** [sweIhm/sweiproject-tg1b-5#4]
Als Verfasser eines alten Beitrags möchte ich diesen ändern, um Rechtschreibfehler zu korrigieren.

Akzeptanzkriterien:
- Der Beitrag muss den User als Verfasser erkennen
- Der User muss den Beitrag editieren können 
- Der veränderte Beitrag muss den Lesern angezeigt werden

**Comment by hsiehken** [comment]
Code ferig, braucht noch tests

**Comment by hsiehken** [comment]
Test passed, well done.
