### ISSUE TITLE
Bild zum Post hinzufügen

### ISSUE THREAD

**Issue by lorenzSt** [sweIhm/sweiproject-tg1b-5#8]
Als Verfasser eines Posts möchte ich ein Bild zu meinem Post hinzufügen, um ihn mit mehr Leben zu erfüllen.

Akzeptanzkriterien:

- Der Verfasser muss Bilder hochladen können
- Bilder müssen zu dem Post hinzugefügt werden
- Leser müssen das Bild sehen neben dem Text sehen können

**Comment by hsiehken** [comment]
Fully tested.
