### ISSUE TITLE
Aktivität erstellen

### ISSUE THREAD

**Issue by lorenzSt** [sweIhm/sweiproject-tg1b-5#9]
Als Professor möchte ich eine Aktivität erstellen, die in der Aktivitäts-Map angezeigt wird, um dafür zu werben.

Akzeptanzkriterien:

- Email verifizieren
- Aktivität erstellen
- Aktivität in der Map einfügen
- Aktivität Betrachtern anzeigen

**Comment by hsiehken** [comment]
duplicated issue
